# Generated by Django 5.0.2 on 2024-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='volume',
            field=models.CharField(max_length=20),
        ),
    ]
