# Generated by Django 5.0.2 on 2024-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockmarketdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='close',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='high',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='low',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmarketdata',
            name='open',
            field=models.CharField(max_length=20),
        ),
    ]
